name: dslab
channels:
  - python
dependencies:
  - python=3.11
  - torch==2.1.0+cu118
  - pandas==2.1.3
  - transformers==4.35.2
  - lightning==2.1.2
  - tokenizers==0.15.0
  - tqdm==4.66.1
  - scikit-learn==1.3.2
  - numpy==1.24.1
  - torchmetrics==1.2.1
  - wandb==0.16.5